// Generated by scripts/generate-char-manifest.mjs — do not edit by hand.
export const charManifest = {
  "viewBox": "0 0 296 374",
  "arms": {
    "armL": {
      "jointId": "armL_joint",
      "pivotX": 0,
      "pivotY": 0,
      "sleeveIds": [
        "path124",
        "path126"
      ]
    },
    "armR": {
      "jointId": "armR_joint",
      "pivotX": 0,
      "pivotY": 0,
      "sleeveIds": [
        "path125",
        "path127"
      ]
    }
  },
  "fillables": [
    {
      "id": "path45",
      "key": "path45",
      "label": "Skin",
      "defaultFill": "#ddae67",
      "targetIds": [
        "path45",
        "path1",
        "path1-3"
      ]
    },
    {
      "id": "path65",
      "key": "path65",
      "label": "Pants",
      "defaultFill": "#5042ae"
    },
    {
      "id": "hair_fill",
      "key": "hair_fill",
      "label": "Hair",
      "defaultFill": "#311e00",
      "targetIds": [
        "path85",
        "path87-4",
        "path87-4-4",
        "path91",
        "path94",
        "path95",
        "path96",
        "path99",
        "path97",
        "path100"
      ]
    }
  ],
  "globalFillGroups": [
    {
      "key": "shirt",
      "label": "Toggleshirt",
      "parentId": "layer15",
      "defaultFill": "#261b4f",
      "targetIds": [
        "path67",
        "path118",
        "path119",
        "path120"
      ]
    },
    {
      "key": "sleeves",
      "label": "Togglesleeve",
      "parentId": "layer19",
      "defaultFill": "#261b4f",
      "targetIds": [
        "path124",
        "path125",
        "path126",
        "path127"
      ]
    }
  ],
  "toggleGroups": [
    {
      "key": "layer15",
      "label": "Toggleshirt",
      "parentId": "layer15",
      "defaultOption": "path67",
      "options": [
        {
          "id": "path67",
          "label": "Tshirt"
        },
        {
          "id": "path118",
          "label": "Longshirt"
        },
        {
          "id": "g120",
          "label": "Crop"
        }
      ]
    },
    {
      "key": "layer16",
      "label": "Togglehair",
      "parentId": "layer16",
      "defaultOption": "g96",
      "options": [
        {
          "id": "g89",
          "label": "Long"
        },
        {
          "id": "g93",
          "label": "Short"
        },
        {
          "id": "g96",
          "label": "Pony"
        }
      ]
    },
    {
      "key": "layer17",
      "label": "Togglemouth",
      "parentId": "layer17",
      "defaultOption": "g103",
      "options": [
        {
          "id": "path51-8",
          "label": "Positive"
        },
        {
          "id": "g103",
          "label": "NEU"
        },
        {
          "id": "path51-8-5",
          "label": "Negative"
        }
      ]
    },
    {
      "key": "layer18",
      "label": "Toggleeyecolour BLK",
      "parentId": "layer18",
      "defaultOption": "g105",
      "options": [
        {
          "id": "g104",
          "label": "Default"
        },
        {
          "id": "g105",
          "label": "Brown"
        },
        {
          "id": "g107",
          "label": "Blue"
        }
      ]
    },
    {
      "key": "layer19",
      "label": "Togglesleeve",
      "parentId": "layer19",
      "defaultOption": "g127",
      "options": [
        {
          "id": "g125",
          "label": "Longshirtsleeve"
        },
        {
          "id": "g127",
          "label": "Shortsleeve"
        }
      ]
    },
    {
      "key": "blush",
      "label": "Blush",
      "parentId": "g102",
      "defaultOption": "on",
      "options": [
        {
          "id": "on",
          "label": "On"
        },
        {
          "id": "off",
          "label": "Off"
        }
      ],
      "elementId": "g102"
    }
  ],
  "appearanceDefaults": {
    "fills": {
      "path45": "#ddae67",
      "path65": "#5042ae",
      "hair_fill": "#311e00",
      "shirt": "#261b4f",
      "sleeves": "#261b4f"
    },
    "toggles": {
      "layer15": "path67",
      "layer16": "g96",
      "layer17": "g103",
      "layer18": "g105",
      "layer19": "g127",
      "blush": "on"
    }
  },
  "blink": {
    "openLayerIds": [
      "layer14",
      "layer18",
      "g100"
    ],
    "closedLayerId": "g11",
    "closedDurationMs": 120,
    "minIntervalMs": 2000,
    "maxIntervalMs": 4500
  },
  "headshotViewBox": "0 0 100 100",
  "assets": {
    "character": "char/charprod.svg",
    "headshot": "char/headshot.svg"
  }
} as const

export type CharManifest = typeof charManifest
export type CharacterPoseId =
  | 'idle'
  | 'present'
  | 'think'
  | 'write'
  | 'shop'
  | 'wave'
