// Generated by scripts/generate-char-manifest.mjs — do not edit by hand.
export const charManifest = {
  "viewBox": "0 0 296 374",
  "arms": {
    "armL": {
      "jointId": "armL_joint",
      "pivotX": 0,
      "pivotY": 0,
      "sleeveIds": [
        "path124",
        "path126"
      ]
    },
    "armR": {
      "jointId": "armR_joint",
      "pivotX": 0,
      "pivotY": 0,
      "sleeveIds": [
        "path125",
        "path127"
      ]
    }
  },
  "fillables": [
    {
      "id": "path45-8-4",
      "key": "path45-8-4",
      "label": "Skin",
      "defaultFill": "#040302"
    },
    {
      "id": "path45-8",
      "key": "path45-8",
      "label": "Skin",
      "defaultFill": "#ddae67"
    },
    {
      "id": "path45",
      "key": "path45",
      "label": "Skin",
      "defaultFill": "#ddae67",
      "targetIds": [
        "path45",
        "path45-8",
        "path1",
        "path1-0",
        "path1-3",
        "path1-0-2"
      ]
    },
    {
      "id": "path45-4",
      "key": "path45-4",
      "label": "Skin",
      "defaultFill": "#ddae67"
    },
    {
      "id": "path65",
      "key": "path65",
      "label": "Pants",
      "defaultFill": "#6d7b9a"
    },
    {
      "id": "hair_fill",
      "key": "hair_fill",
      "label": "Hair",
      "defaultFill": "#311e00",
      "targetIds": [
        "path85-7",
        "path85",
        "path87-4",
        "path87-4-4",
        "path1127-8",
        "path1127-2-6",
        "path1127-8-7",
        "path1127-2-6-0",
        "path1127-3-00",
        "path1127-2-0-8",
        "path1128-7",
        "path1129-6",
        "path1129-6-4",
        "path90",
        "path91",
        "path1127-3-0",
        "path1127-2-0-9",
        "path1127-6",
        "path1127-2-49",
        "path93",
        "path94",
        "path95",
        "path96",
        "path99",
        "path97",
        "path100",
        "path1127",
        "path1127-2",
        "path1127-9",
        "path1127-2-4",
        "path1127-9-9",
        "path1127-2-4-9",
        "path1127-3",
        "path1127-2-0",
        "path1128",
        "path1132",
        "path1129"
      ]
    },
    {
      "id": "g86",
      "key": "catbase",
      "label": "Catbase",
      "defaultFill": "#ffce67",
      "targetIds": [
        "path77-0",
        "path78-9",
        "path79-7",
        "path81-1",
        "path82-7",
        "path86-45",
        "path86-4-1",
        "path77",
        "path78",
        "path79",
        "path81",
        "path82",
        "path86",
        "path86-4"
      ]
    },
    {
      "id": "g91-8",
      "key": "dogbase",
      "label": "Dogbase",
      "defaultFill": "#725d34",
      "targetIds": [
        "ellipse86",
        "ellipse87",
        "ellipse88",
        "ellipse89",
        "ellipse90",
        "path92",
        "path92-9",
        "ellipse86-4",
        "ellipse87-5",
        "ellipse88-7",
        "ellipse89-9",
        "ellipse90-8",
        "path92-4",
        "path92-9-5"
      ]
    },
    {
      "id": "path3",
      "key": "bandr",
      "label": "BandR",
      "defaultFill": "#c32033",
      "targetIds": [
        "path3"
      ]
    },
    {
      "id": "path3-0",
      "key": "bandl",
      "label": "BandL",
      "defaultFill": "#c32033",
      "targetIds": [
        "path3-0"
      ]
    },
    {
      "id": "path13-4",
      "key": "watchr",
      "label": "WatchR",
      "defaultFill": "#35090e",
      "targetIds": [
        "path13",
        "path13-4"
      ]
    },
    {
      "id": "path16",
      "key": "glover",
      "label": "GloveR",
      "defaultFill": "#35090e",
      "targetIds": [
        "path16"
      ]
    },
    {
      "id": "path16-0",
      "key": "glovel",
      "label": "GloveL",
      "defaultFill": "#35090e",
      "targetIds": [
        "path16-0"
      ]
    },
    {
      "id": "path10",
      "key": "pocketr",
      "label": "PocketR",
      "defaultFill": "#c32033",
      "targetIds": [
        "path10"
      ]
    },
    {
      "id": "path10-7",
      "key": "pocketl",
      "label": "PocketL",
      "defaultFill": "#2c2460",
      "targetIds": [
        "path10-7"
      ]
    },
    {
      "id": "path21",
      "key": "circle",
      "label": "CIRCLE",
      "defaultFill": "#d38d5f",
      "targetIds": [
        "path21"
      ]
    },
    {
      "id": "rect21",
      "key": "square",
      "label": "SQUARE",
      "defaultFill": "#d38d5f",
      "targetIds": [
        "rect21"
      ]
    },
    {
      "id": "path22",
      "key": "star",
      "label": "STAR",
      "defaultFill": "#d38d5f",
      "targetIds": [
        "path22"
      ]
    },
    {
      "id": "path40",
      "key": "bandana",
      "label": "Bandana",
      "defaultFill": "#800000",
      "targetIds": [
        "path40"
      ]
    },
    {
      "id": "g55",
      "key": "lemmon",
      "label": "Lemmon",
      "defaultFill": "#ffcc00",
      "targetIds": [
        "path54",
        "path54-63",
        "path55"
      ]
    }
  ],
  "globalFillGroups": [
    {
      "key": "shirt",
      "label": "Toggleshirt",
      "parentId": "layer15",
      "defaultFill": "#866a91",
      "targetIds": [
        "path67",
        "path118",
        "path119",
        "path120"
      ]
    },
    {
      "key": "sleeves",
      "label": "Togglesleeve",
      "parentId": "layer19",
      "defaultFill": "#7d6180",
      "targetIds": [
        "path124",
        "path125",
        "path126",
        "path127"
      ]
    }
  ],
  "toggleGroups": [
    {
      "key": "layer15",
      "label": "Toggleshirt",
      "parentId": "layer15",
      "defaultOption": "path67",
      "isAccessory": false,
      "options": [
        {
          "id": "path67",
          "label": "Tshirt"
        },
        {
          "id": "path118",
          "label": "Longshirt"
        },
        {
          "id": "g120",
          "label": "Crop"
        }
      ]
    },
    {
      "key": "layer16",
      "label": "Togglehair",
      "parentId": "layer16",
      "defaultOption": "g96",
      "isAccessory": false,
      "options": [
        {
          "id": "g89",
          "label": "Long"
        },
        {
          "id": "g93",
          "label": "Short"
        },
        {
          "id": "g96",
          "label": "Pony"
        }
      ]
    },
    {
      "key": "layer17",
      "label": "Togglemouth",
      "parentId": "layer17",
      "defaultOption": "g103",
      "isAccessory": false,
      "options": [
        {
          "id": "path51-8",
          "label": "Positive"
        },
        {
          "id": "g103",
          "label": "NEU"
        },
        {
          "id": "path51-8-5",
          "label": "Negative"
        }
      ]
    },
    {
      "key": "layer18",
      "label": "Toggleeyecolour BLK",
      "parentId": "layer18",
      "defaultOption": "g105-0",
      "isAccessory": false,
      "options": [
        {
          "id": "g105",
          "label": "Default"
        },
        {
          "id": "g105-0",
          "label": "Brown"
        },
        {
          "id": "g105-9",
          "label": "Blue"
        }
      ]
    },
    {
      "key": "layer19",
      "label": "Togglesleeve",
      "parentId": "layer19",
      "defaultOption": "g127",
      "isAccessory": false,
      "options": [
        {
          "id": "g125",
          "label": "Longshirtsleeve"
        },
        {
          "id": "g127",
          "label": "Shortsleeve"
        }
      ]
    },
    {
      "key": "layer2",
      "label": "Togglepet",
      "parentId": "layer2",
      "defaultOption": "g86",
      "isAccessory": true,
      "options": [
        {
          "id": "g86",
          "label": "Catbase",
          "companionIds": [
            "g86-0"
          ]
        },
        {
          "id": "g91-8",
          "label": "Dogbase",
          "companionIds": [
            "g91"
          ]
        }
      ],
      "followVisibilityIds": [
        "path1236",
        "path1236-0"
      ]
    },
    {
      "key": "layer18-6",
      "label": "Toggleeyecolour BLK",
      "parentId": "layer18-6",
      "defaultOption": "g105-1",
      "isAccessory": false,
      "options": [
        {
          "id": "g104-5",
          "label": "Default"
        },
        {
          "id": "g105-1",
          "label": "Brown"
        },
        {
          "id": "g107-1",
          "label": "Blue"
        }
      ]
    },
    {
      "key": "layer3",
      "label": "Togglewrist",
      "parentId": "layer3",
      "defaultOption": "path3",
      "isAccessory": true,
      "options": [
        {
          "id": "path3",
          "label": "BandR"
        },
        {
          "id": "path3-0",
          "label": "BandL"
        },
        {
          "id": "g15",
          "label": "WatchR"
        },
        {
          "id": "g15-5",
          "label": "WatchL"
        },
        {
          "id": "path16",
          "label": "GloveR"
        },
        {
          "id": "path16-0",
          "label": "GloveL"
        }
      ]
    },
    {
      "key": "layer4",
      "label": "Togglepants",
      "parentId": "layer4",
      "defaultOption": "path10-7",
      "isAccessory": true,
      "options": [
        {
          "id": "path10",
          "label": "PocketR"
        },
        {
          "id": "path10-7",
          "label": "PocketL"
        }
      ]
    },
    {
      "key": "layer5",
      "label": "Toggleshoes",
      "parentId": "layer5",
      "defaultOption": "g16",
      "isAccessory": true,
      "options": [
        {
          "id": "g16",
          "label": "BOOTS"
        },
        {
          "id": "g20",
          "label": "SNEEKER"
        },
        {
          "id": "g21",
          "label": "HEEL"
        }
      ]
    },
    {
      "key": "layer6",
      "label": "Toggleshirt",
      "parentId": "layer6",
      "defaultOption": "path22",
      "isAccessory": true,
      "options": [
        {
          "id": "path21",
          "label": "CIRCLE"
        },
        {
          "id": "rect21",
          "label": "SQUARE"
        },
        {
          "id": "path22",
          "label": "STAR"
        }
      ]
    },
    {
      "key": "layer7",
      "label": "Toggleface",
      "parentId": "layer7",
      "defaultOption": "g27",
      "isAccessory": true,
      "options": [
        {
          "id": "g27",
          "label": "Glassessquare"
        },
        {
          "id": "g32",
          "label": "Glassescircle"
        },
        {
          "id": "path40",
          "label": "Bandana"
        },
        {
          "id": "g47",
          "label": "Mask"
        }
      ]
    },
    {
      "key": "layer8",
      "label": "Togglehat",
      "parentId": "layer8",
      "defaultOption": "g51",
      "isAccessory": true,
      "options": [
        {
          "id": "g51",
          "label": "Cowboy"
        },
        {
          "id": "path52",
          "label": "Headcover"
        },
        {
          "id": "path53",
          "label": "Crown"
        }
      ]
    },
    {
      "key": "blush",
      "label": "Blush",
      "parentId": "g102",
      "defaultOption": "on",
      "options": [
        {
          "id": "on",
          "label": "On"
        },
        {
          "id": "off",
          "label": "Off"
        }
      ],
      "elementId": "g102"
    }
  ],
  "appearanceDefaults": {
    "fills": {
      "path45-8-4": "#040302",
      "path45-8": "#ddae67",
      "path45": "#ddae67",
      "path45-4": "#ddae67",
      "path65": "#6d7b9a",
      "hair_fill": "#311e00",
      "catbase": "#ffce67",
      "dogbase": "#725d34",
      "bandr": "#c32033",
      "bandl": "#c32033",
      "watchr": "#35090e",
      "glover": "#35090e",
      "glovel": "#35090e",
      "pocketr": "#c32033",
      "pocketl": "#2c2460",
      "circle": "#d38d5f",
      "square": "#d38d5f",
      "star": "#d38d5f",
      "bandana": "#800000",
      "lemmon": "#ffcc00",
      "shirt": "#866a91",
      "sleeves": "#7d6180"
    },
    "toggles": {
      "layer15": "path67",
      "layer16": "g96",
      "layer17": "g103",
      "layer18": "g105-0",
      "layer19": "g127",
      "layer2": "g86",
      "layer18-6": "g105-1",
      "layer3": "path3",
      "layer4": "path10-7",
      "layer5": "g16",
      "layer6": "path22",
      "layer7": "g27",
      "layer8": "g51",
      "blush": "on"
    }
  },
  "blink": {
    "openLayerIds": [
      "layer14",
      "layer18",
      "g100",
      "layer14-9",
      "layer18-6",
      "g100-4"
    ],
    "closedLayerIds": [
      "g11",
      "g11-7"
    ],
    "closedLayerId": "g11",
    "closedDurationMs": 120,
    "minIntervalMs": 2000,
    "maxIntervalMs": 4500
  },
  "headshotViewBox": "0 0 100 100",
  "assets": {
    "character": "char/charprod.svg",
    "headshot": "char/headshot.svg"
  }
} as const

export type CharManifest = typeof charManifest
export type CharacterPoseId =
  | 'idle'
  | 'present'
  | 'think'
  | 'write'
  | 'shop'
  | 'wave'
